name: API CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/python/api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: services/python/api/requirements.txt
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run tests
        env:
          ALLOW_UNAUTH_WRITE: 'false'
        run: pytest -q


